### ISSUE TITLE
Invalid callback

### ISSUE THREAD

**Issue by DvIMPact** [Autodesk-Forge/forge.commandline-nodejs#5]
After using the tool to delete a bucket, I get a callback error :

```bash
C:\Users\{*}\forge.commandline-nodejs-master>node forge-cb.js bucketDelete {bucketname}
WARNING: The 'forge-oauth2' npm package is deprecated in favor of the 'forge-apis' npm package, please upgrade.
WARNING: The 'forge-oss' npm package is deprecated in favor of the 'forge-apis' npm package, please upgrade.
WARNING: The 'forge-data-management' npm package is deprecated in favor of the 'forge-apis' npm package, please upgrade.
WARNING: The 'forge-model-derivative' npm package is deprecated in favor of the 'forge-apis' npm package, please upgrade.
Delete bucket: {bucketname}
bucket deleted
fs.js:136
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:136:11)
    at Object.unlink (fs.js:943:14)
    at C:\Users\{*}\forge.commandline-nodejs-master\forge-cb.js:340:88
    at FSReqWrap.oncomplete (fs.js:154:5)
```

However the bucket is still deleted. Don't know if I'm doing somethin wrong or if it comes from the tool/the files in the bucket.

**Comment by DvIMPact** [comment]
"Solved the issue" by changing the lines 340, 341 in forge-cb.js :
```javascript
fs.stat (__dirname + '/data/bucket', function (err, stat) { if ( err === null ) fs.unlink (__dirname + '/data/bucket') ; }) ;
fs.stat (__dirname + '/data/' + bucketKey + '.bucket.json', function (err, stat) { if ( err === null ) fs.unlink (__dirname + '/data/' + bucketKey + '.bucket.json') ; }) ;
```
into :
```javascript
fs.statSync (__dirname + '/data/bucket', function (err, stat) { if ( err === null ) fs.unlink (__dirname + '/data/bucket') ; }) ;
fs.statSync (__dirname + '/data/' + bucketKey + '.bucket.json', function (err, stat) { if ( err === null ) fs.unlink (__dirname + '/data/' + bucketKey + '.bucket.json') ; }) ;
```
I don't have the error message anymore, however since I don't understand what caused this error I don't close the issue yet.

**Comment by cyrillef** [comment]
I rewrote the tool, so this error should go away now.
